### ISSUE TITLE
Issue Creating Addon on Windows

### ISSUE THREAD

**Issue by shullsa** [ibm-maximo-dev/maximodev-cli#1]
When creating an addon with Java support on Windows it fails if the Maximo home is using a single backslash (like C:\Users\sshull\Desktop\maximo). If you replace it with forward slash it works.

![2018-04-23_10-13-30](https://user-images.githubusercontent.com/12107049/39132377-b3122c94-46df-11e8-8288-446242c82f88.png)

**Comment by stuckless** [comment]
@shullsa Thanks, I will test this again on windows... I did do run through but I'm thinking that something crept into this.  Our primary testing has been on Linux and Mac so far.

**Comment by stuckless** [comment]
@shullsa this is fixed in maximodev-cli 1.0.5.  NOTE:  the package is renamed from maximo-cli to maximodev-cli.  So you will need to unininstall and reinstall the package as maxiodev-cli.
