### ISSUE TITLE
Unable to Create Java Field Validator

### ISSUE THREAD

**Issue by shullsa** [ibm-maximo-dev/maximodev-cli#2]
Executing maximodev-cli create java-field-validator or maximodev-cli create jfv fails saying it can't find module maximodev-cli-create-java-field-validator. For what it's worth, I did use the -g flag when installed via NPM and removed the old maximo-cli and still seeing the same error. 

![2018-04-23_14-31-56](https://user-images.githubusercontent.com/12107049/39145887-276903ba-4703-11e8-90c6-4651db2faad1.png)

**Comment by stuckless** [comment]
This command (along with the create script validator) (plus a few other commands) have been removed from public use.  Some of these are basically work in progress things that should not be enabled by default.  Version 1.0.6 suppresses the work in progress commands.
