### ISSUE TITLE
Invalid Commands Don't Error

### ISSUE THREAD

**Issue by shullsa** [ibm-maximo-dev/maximodev-cli#3]
When trying to test the maximodev-cli create script-field-validator mentioned in the readme it didn't do anything. After reviewing the code it seems like that was commented out for the time being, which is fine. It'd be nice if someone mistypes something or tries to execute an invalid command for it to error out instead of doing nothing (I was looking in the folders to try and see what it created before realizing it didn't create anything).

For example, if I type maximodev-cli ignorethis or maximodev-cli create test it should error out that it isn't a valid request.

**Comment by stuckless** [comment]
1.0.6 has been created and fixes this issue.  (if you pass an invalid command, it will print an error)
