### ISSUE TITLE
Getting error while build 

### ISSUE THREAD

**Issue by arerchetan123** [ibm-maximo-dev/maximodev-cli#5]
Getting error while build 
![capture](https://user-images.githubusercontent.com/43139642/45298509-55f05a80-b526-11e8-9ee3-e6a7cecde27a.PNG)

And checked addon properties file and maximo home is set
![image](https://user-images.githubusercontent.com/43139642/45298611-b1224d00-b526-11e8-912b-199e5df12858.png)

Not NOde.js developer but looks like issue is in this file at line 28
![image](https://user-images.githubusercontent.com/43139642/45298727-078f8b80-b527-11e8-9f10-2cb76740f083.png)

**Comment by stuckless** [comment]
Thanks for the bug.  I found the problem, and a new version has been published to npm.  You should be able to intsall/update and try again.  Thanks!
